[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "old_post/markdown-syntax"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/pranav083"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/pranav083"

[[main]]
  name = "About"
  url = "about/"
  weight = -107