[[main]]
  name = "Home"
  url = ""
  weight = -110
[[main]]
  name = "Gallery"
  url = "2020/update"
  weight = -108
[[main]]
  name = "Archives"
  identifier = "Archives"
  weight = -109
[[main]]
  parent = "Archives"
  name = "2020"
  url = "2020/markdown-syntax"
  weight = -112 
[[main]]
  parent = "Archives"
  name = "2021"
  url = "post/lvgl_esp32_setup"
  weight = -111  
# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "LinkedIn"
  url = "https://www.linkedin.com/pranav083"
[[main]]
  parent = "Links"
  name = "Twitter"
  url = "https://twitter.com/pranav083"

[[main]]
  name = "About"
  url = "about/"
  weight = -107